# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "dev_requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            python3 -m venv venv
            . venv/bin/activate
            pip install  -q -r dev_requirements.txt

            sudo apt-get install python3 python3-dev virtualenv \
            texlive-pictures texlive-science texlive-latex-extra \
            imagemagick

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "dev_requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod a+x doc_building/create_doc_files.sh
            bash testall.sh

      - persist_to_workspace:
          #root: doc_building/build
          # get docs working first then remove
          root: doc_building/build
          paths: html

      - store_artifacts:
          path: test-reports
          destination: test-reports
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: doc_building/build
      - run:
          name: Disable jekyll builds
          command: touch doc_building/build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "mrichards7@outlook.com.au"
            git config user.name "Matthew Richards (CircleCI Documentation)"
      - add_ssh_keys:
          fingerprints:
            - "00:99:d1:3e:b9:7c:87:e3:1e:3e:cc:0d:c8:7d:78:a1"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Update Documentation"
          --dist doc_building/build/html/


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master

